apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: cluster1
  namespace: ns1
spec:
  distribution:
    version: v1.20
  topology:
    controlPlane:
      count: 1
      class: best-effort-medium
      storageClass: wcp
    workers:
      count: 2
      class: best-effort-medium
      storageClass: wcp
